language: elixir
sudo: required
cache:
  directories:
    - deps
    - _build
services:
  - docker
elixir:
  - 1.4.2
otp_release:
  - 19.3
env:
  global:
    - MIX_ENV=test
    - DOCKER_HUB_ACCOUNT=edenlabllc
    - MAIN_BRANCHES="master develop staging" # Branches on which you want version to be incremented
    - RELEASE_BRANCH="master"
    - HEROKU_APP_NAME="ael"
    - secure: "CuSNUHcRy6X7AkLLDerH6qrVnxHMUjG1ke9aSjxdhKEjhQ1lIBlVVpz6X3lyvJIZt+nGfu/qGUSDVUucMpXL22Th4BU/2cTOVv+RDd9bHGIePZtZC4ehWhucKgSqSEhDSmSq4Qd7YFmNPSuRDIcHiukQPiPAq5RrZw3zw1HvQWPM/BmIyg1IgAl3tHf8uLisjzenIjwVPELlF15M1c6Lrfe/YVtS3TpnWgdsMGR6IjZU2NkbRqW+/FPmP1socetshpxn0RXgMgkLbz1CdCbVYIfPGBq4QKMafXncGC39MaiA3nm3gBL/Tn3CWk7MC0jPZLwex72n9Dc32lQpomFBzubk8ufsCSKR+GHf7lUKq8K2uUJRvAb0LI5Q+YOWVSrHiEp8e+R4Jbz1CiqmS5LZG7pBp0n9WHbV+ra51zCcHOIiv+uB2mR9krkbw8Ehm5/bFL2mHb11ztEs9mAcm4w29ZhBIQ+tZLsVIM/ignLasEmizRk2U2nsW1asai/YYI2LCY+Cj+0mLldY1KfQoMN5nN+oj8L2Qszt+Sww5mjPbHbfWfY2daZyvwcXXox/N7MYoTYNtSWEXHmtHd0yMFCgUzclOv/4xjqkfSbmX7XpTmiVxHcgeRAmx/9cfyw0w4MgJJz7/8cw+vdLGhM8IclH/34QsJwd+yK4378GDlyVuwY="
    - secure: "RuDDqaIWdShDYY3LMorGEQNiLXqrzErlQNTd0XPuajczKzYvl6lq4k93Ohu0t81/NQK06zD8xz25pmS4ogBA1HiMbDS95D/liUnE7AunKyjKG04tEuOdXMTm4Q/2QKHbugZp7iE/0RR+0jdJXrvzWwk2Dq9Yt293L+CsHgldEdil0nr/bAjGnWy3xT2IIq/nuZmJarTZnzfROrXMrB+5CaHm5Iw3klvSsnekAPRamZ9F+Q8Ko4NWcm9dOpCPlZUEvR+Ekegt2LukLLUA7N/KULhAp6KLS8PrZiwM8Wc+x8WqeZgUmzij2gdoV/kvghVlJFMg5Xy4o2kXEF66wQL/eJffpP4Spgg0ZZjPLr4PFgE4pxps2IwnTSApFzMOxFY9lb0JWXm0BgPjXXXWJBl/IZaHK0URoSeARazly97LpQtmHecqMn9CAhs8Yhty/yfRSr1sspT7DS7uwbbPMmudtLb9Zqk2E2fm1WQQO7rNrLdZLZjlk8pWsk48Dm0OWc3O6qGstvnJayeYAiZ4vK2JQnhodjSA1v9XlLhjwSSE0Iv4eEteB12JmY3tlM0SwdTM7BOBvQs1woj7vzmtuWbCq4WWTAEPNBlRroG+eUHBW2rQQJIPSkHBK8L4rq8meivxvA9tyA57ZxJqbCf0a7vmleUCNedlTPuuhu7QcJdCmjg="
    - secure: "A28VAicvlcqprk446xKHlTU73H/qUoxfWml6efHoxQx4/aKsNNDk3ty+1NgNEmgvMmhb1JCYgBq7psPx/JaYr3quTAmB3vv94X3sSUFThDp01CK46paMNybdqhPD9uRSrl7QfTSgCyMGSFFVDK+Ld6kKY9RH/68h8BTnrbg3wU5o5Oa3rrJrIjRp2+VKV0FSWNi2P6haF9oBaHtmBn5nH9Ss+FZsXTSv7hYz6SZ2b5ao9LGD6XQ2QKBq7rJHy/O2+cz6ccswvR716kWOLTCFCKFMCVk57ltbYE+bfeXQYGidUWv3Fpfq83sf+NXy5Kfva9SyblktAuRh695WonBQ0HlYHwJ0pP42ITIugqJWHyuAlqsHKWxBprxD4Tueh0FZ18eDkwtjRpjgIBnkUuuwlaCdHPlvgpM4JwEleTlE6nkz+LrxdDJXFNgyaZ3dc8S5wK7T3XxEJXJeWEwcDjDpmk/pQ9fOYYTpIU8XoeBLS6/Q4wsO9q/QqvpCGgUJ0KdgxnFTPH+Dx4tMwBqrBs5n84ec5lh6Mk5g9U0XOpi6zDbZn9pn+G626kiBnc3Dw3NEWoOhiNO7BaCeImnbHK4pcfV9P8GyDB4dcS9FyzPLQQ+62ntC/oVymAA5sLM+J2PU/K6EKKpSdwrQY4Xj1rfvP6rCrIly/vH4McoBQkz8eiA="
branches:
  # Releases are generated automatically, stop infinite build loop
  except:
    - /[0-9]*\.[0-9]*\.[0-9]*/
before_install:
  openssl aes-256-cbc -K $encrypted_2fbea6458a09_key -iv $encrypted_2fbea6458a09_iv -in priv/secret.enc -out priv/service_account_key.json -d
script:
  # Increment version in mix.exs
  - ./bin/ci/version-increment.sh
  # Install dependencies if Travis won't do it by default
  # - mix deps.get
  # Run all tests except pending ones
  - mix test --exclude pending --trace
  # Submit code coverage report to Coveralls
  # Add --pro if you using private repo.
  - mix coveralls.travis --exclude pending
  # Run static code analysis
  - mix credo --strict
  # Check code style
  - mix dogma
  # Build Docker container
  - ./bin/build.sh
  # Run Docker container
  - sudo ./bin/start.sh
  - sleep 5
  - docker ps
  - RUNNING_CONTAINERS=`docker ps | wc -l`;
    if [ "${RUNNING_CONTAINERS//[[:space:]]/}" == "1" ]; then
      echo "[E] Container is not started\!";
      docker logs ael_api --details --since 5h;
      exit 1;
    fi;
  # Run acceptance tests on Docker container
  - "CONTAINER_HTTP_HOST=localhost CONTAINER_HTTP_PORT=4000 mix test test/acceptance"
after_failure:
  - docker logs ael_api --details --since 5h
after_success:
  # Submit Docker container to Docker Hub and create GitHub Release by pushing tag with changelog
  - ./bin/ci/push.sh
  # CD to Heroku
  - ./bin/ci/deploy.sh
