language: elixir
sudo: required
cache:
  directories:
    - deps
    - _build
services:
  - docker
elixir:
  - 1.4.2
otp_release:
  - 19.3
notifications:
  slack: 
    rooms:
      - secure: "IK/yEPDepy0i0RC9/OAUWSq7F552zJf553hRzApjNk8RD7XT8ZPsAdsgXZ9oCWkuB+U7d1ZJ2adVUn75+fSIAn0IijFZK2tz8lhvBhileRgLKxshT/oUO4ihZmm+f4AKFw896qaVHqEIJF8QPwzaZh7qlCmmVoCc8luwQTzlsvTziOjJcbxZmn+IOEDUGmvQZem1Bh0O0Lr8nrXHD4C3dKFuWqRhlY6NmkixdPnY/4Tfs4qmZVdSQ8p1FeUcvP9dov+Fehj+wIUxAcGscxNQ3j3i1CrLyEKGijcaUwMKPx8Yz/OfjJU9oP5GUyUhD9zosHukg0SnMWWMtwjK+V++PSGwP79L1kwIVSOqc/57ZJEqRMGxHsBccCbsAUkX03rjlomS4g5dGd+Rzg99Gvz2CJ3hnfeqOkpGsDLbA6HUato5plM+uBDpofw5vcmThYMRDpxZ11XKNnz0Sx+dfavVwqInQGJJn/k4Ty3BT+nZ9S16BjJqU5l6LeofZEby6rhgGdEfB7/dppqnqD2YfQ9VMyJ48g5q6/yq8tTkB5lfibd7eG5PDbkeGP1HpLOnnDachsrw12bxyhIq0tCfMfRJdrXbXI7Vfnwz95URnDU8+n0EqiqYXXBACtASflW1GDpLps4hAN0UmgtvvU7U5ssl5pogS55cERONgJWc+m5Scrg="
    on_success: always
env:
  global:
    - Chart=ael
    - MIX_ENV=test
    - DOCKER_HUB_ACCOUNT=edenlabllc
    - MAIN_BRANCHES="master develop staging" # Branches on which you want version to be incremented
    - RELEASE_BRANCH="master"
    - HEROKU_APP_NAME="edenlabllc-ael"
      # HEROKU
    - secure: "T/CbMk6DTZPNzRAlAEsOZplOyhmGKnP8X1OGBEzL39elPm8WKCJHadiAKx06SnABwxzbBAhhYtvEH8PCLZFE93d3S1c0kv2muyChHlGqc2TxlkDbztjkKPBYwMEgISY1YB6MQK8Kse7wWbHAjhj0CQVccl/eWu3jMal2wUV0ORshpwbhf/q4YogYDi6DOzwlQXkrcpJASkuFMxeiZwGsC5hXp0zJJrB0hBA4cpWtqehFlVrNVx/kHyDR8Gi9Fbbgf2QgA4mHdr94xtrULi40OeoLVL3exzNaR1SnbwYS/MIWHWI5Udtg+XZoWfsTZalHGlD4RcvQrbzf2XDTTo+4JQT0/rgHZubx+mlWaeqOevsex/akmz9ns2i1THOjIHeF+l+J0yG+PvqLZjEXRYwmSjiek6bkoAUZBBg7N2+k4R+xvfOT4BVkyzXz8NMk9HoAK5tbCH/LRR+ttZwhMppp0/UnqBeSS1t9FFQ730ggFaeeKRw89C3Ili4WJnbl/oN6Z1Ub5fCU6MyjmgaJKSHTGdugL8WjY6xX3vI2U4DiE0astxfPC1xA63+Xf4ytLYN4cLF81ZRziWYJCA9eTazrzR+/+dj8TL3w2d0pHGgA/+EuibayvirVGb41NVgBlQMyd+8oFIK8e+GpKsyaKbV02DCafRJVLQMgV5Blra7art8="
      # DOCKER
    - secure: "m5kINtUT49oLBdrKjJQOIeDEO6K3RBvN4cDNpBb6/9pKNPw8SWUcnfub+mHEKnC997uY7ZGN45cpOfQhwWe5waF1j6j46rHcwaysLPknSipsW5WbJnrFTHQd/SOO6csRBba4bQpcMLSZ6eQulEHZ5OYPB/glTeIx9Q6DztzgJeHHtQcGsok5C8NuyKmg8K/K3xWx8chqZYOIvSKHZUZDFbRAHxl1TPMMqCfTZxeoQahgHlohYQBINrRW+hf0Uh7vGv651PMxdVKZTPBhoOUOKTXoXfNintk1XW7ayN8WAhtBtkh1R1K4dAofOLHFyspbB1KBJIgXjJEqoKd+VQuMEJUysdP3N62khR3A8m+SGab8PKuuRaDIWrYwR5o8nTxMabQA9PoTidDXP3XJDX5kNCXhdL9itzVWtHP6sF3hk2SlN/gQDdAs8jKVFrAw37s1NnGSb5xqTi+8XhzdNiBv8FDK7J4ltz2o0jfy22iW2HyCBDDqffBg2Wz3hn9rvhU7YWg4ztXLqZ/a7tO0XpXyFh+DSHLsiP5Cr1rBPaaNRqO8x9mCjqUlWQ20lZUphJ39+rPw2COhet7LWkGzf9wVtvkJYBdMfhWpz232xjWiZSM53XWG0UfikmAUrzbCpQjWTrL3vXc0LpoXHAI6vACucQXC4Nt3hgVcpNlM1RwWeFI="
      # GITHUB
    - secure: "c9T4gKC65WulbO7WkJs1TBtMmYbUrUDDjvg4AIDg2XpfelNWQcT6ege5/4yTkF5ccOSC1hXtMz2+d5wnQ6Er53cvL+2KMhVi7qeGx2sJHw93T880Bm83YDz9LnSSLRQIdGw9copXqNoW7MPO5KjNrprBldTHOK9UwIBW6dtFj3l5/5TATu/7F8xN4SfVCHlAQnHdtWCpJpQ2Rbkio+s+XPaVe+dB+MMRUiQSxFUItR20XrsSkKbm4pwn3PQpbtRBDrLc1LAvjJVEjFbD0PUXJkDXUuGoJMEvtz/NP2wccfYFL2vxKtAKBxwNaH3VZxVWzoOJi5n9QhRu+4QbupMk0ALtL1Hf2jy8zzP5ebfJ+/gVxSzEnv36as63YQFdc0u4Plh5yRnkcpqYPXhu2W3eoge1uZCY+QzJJGid7DDD5RgUUazNcriwT997L92oC04XUPKLvOwEF+kKN+9R8tpzgUgJ9B4xydd0iOqNlompWxnWnmu6lfICRgE7QSFwfXE81heLOP6m1thHKetlrc3lW6PovaS61eKghPm5j/YBCPz0YbBw5DXSSscraN0ojT4fZycNMmgrui9akPToOKasFFPDK8zSV+6VaocGp4VQwUuLXWHYaLo3Gvi5L5gbXNoBCMTkb6eKjwTi7f92Tvo41Q6K/Jufqh6AoRF+M5Nr9DI="
branches:
  # Releases are generated automatically, stop infinite build loop
  except:
    - /[0-9]*\.[0-9]*\.[0-9]*/
before_install:
  - openssl aes-256-cbc -K $encrypted_ace37a1e91cc_key -iv $encrypted_ace37a1e91cc_iv -in eHealth-eef414faa06b.json.enc -out eHealth-eef414faa06b.json -d
  - openssl aes-256-cbc -K $encrypted_ee0aec3588c4_key -iv $encrypted_ee0aec3588c4_iv -in priv/secret.enc -out priv/service_account_key.json -d
script:
  # Increment version in mix.exs
  - ./bin/ci/version-increment.sh
  # Install dependencies if Travis won't do it by default
  # - mix deps.get
  # Run all tests except pending ones
  - ./bin/mix_tests.sh || travis_terminate 1
  # Build Docker container
  - ./bin/build.sh || travis_terminate 1
  # Run Docker container
  - sudo ./bin/start.sh || travis_terminate 1
  # Run acceptance tests on Docker container
  - "CONTAINER_HTTP_HOST=localhost CONTAINER_HTTP_PORT=4000 mix test test/acceptance"
  # Submit Docker container to Docker Hub and create GitHub Release by pushing tag with changelog
  - ./bin/ci/push.sh || travis_terminate 1
  # CD to Dev
  - sudo ./bin/deploy.sh || travis_terminate 1
after_success:
    # CD to Heroku
  - ./bin/ci/deploy.sh 
